namespace test.schema;
schema TestSchema;

@myprop({"a": true,
         "b": null,
         "c": [1,2,3,4],
         "d": "DDDD"})
@myOtherProp("alma")
record TestSchema {
    @checkListProps({
        "stringList": ["one", "two", "three"],
        "objectList": [{"key1": "value1"}, {"key2": "value2"}],
        "listList": [[1,2], [3,4], [5,6]],
        "mixedList": [1, "two", {"key": "value"}, [7,8]]
    })
    string field1;
    decimal(18,2) field2;
    @logicalType("alma")
    int myLogicalType;
    /**
    This is an array field
    */
    array<int> field3;
}